### ISSUE TITLE
FindFilesystem is cumbersome when cross-compiling

### ISSUE THREAD

**Issue by r-burns** [vector-of-bool/CMakeCM#10]
FindFilesystem is cumbersome when cross-compiling due to its use of `check_cxx_source_runs`, which uses `try_run` internally.
See [CMake `try_run` behavior when cross compiling](https://cmake.org/cmake/help/latest/command/try_run.html#behavior-when-cross-compiling).

Is running the resulting executable really necessary? If I modify the module to use `check_cxx_source_compiles` instead, the detection mechanism seems to work just as well, but perhaps I'm neglecting some edge case.

**Comment by r-burns** [comment]
Oh, looks like git blame answers my question.
https://github.com/vector-of-bool/CMakeCM/commit/996aa79960346fc57ebe21fe4a4bfbdea36869aa
Still, I think the ergonomics of this module could be improved by falling back to `check_cxx_source_compiles` when cross-compiling. Happy to draft up a PR if that's an acceptable compromise.

**Comment by vector-of-bool** [comment]
Hello!

Yeah, I was a bit worried if this would become an immediate problem... :sweat_smile:. (See #9).

A PR to switch based on cross-compiling is a totally acceptable compromise.

**Comment by r-burns** [comment]
Did some experimentation in an Ubuntu Eoan docker image - it seems that the segfault can be promoted to a linker error by using -static-libstdc++. So it might be possible to detect that bug on the build machine even when cross-compiling, depending on if there are similar edge cases that need special handling. But I'll keep it simple for now and stick with a fallback to `check_cxx_source_compiles`.
