### ISSUE TITLE
FindFilesystem.cmake: Cannot specify compile features for imported target "std::filesystem"

### ISSUE THREAD

**Issue by tastytea** [vector-of-bool/CMakeCM#7]
OS: Ubuntu Linux bionic (18.04)
CC: g++-7.5.0
CMake: 3.10.2
Log: [logs_FediBlock_backend_1_4.log](https://github.com/vector-of-bool/CMakeCM/files/4848154/logs_FediBlock_backend_1_4.log)

```
CMake Error at cmake/FindFilesystem.cmake:214 (target_link_libraries):
  Cannot specify link libraries for target "std::filesystem" which is not
  built by this project.
Call Stack (most recent call first):
  src/CMakeLists.txt:6 (find_package)
```

[CMakeLists.txt](https://schlomp.space/FediBlock/backend/src/commit/b4c4393cd8e4d6a29dfe742337e47244adf0d417/src/CMakeLists.txt):

``` cmake
find_package(Filesystem REQUIRED COMPONENTS Final Experimental) # Line 6

# […]

target_link_libraries(${PROJECT_NAME}
  PRIVATE PkgConfig::cgicc nlohmann_json std::filesystem)

# […]
```

Works fine with CMake 3.13.4 + g++-8.3.0.

**Comment by vector-of-bool** [comment]
The ability to use `target_*` commands on `IMPORTED` targets was added in CMake 3.11. IS it reasonable to ask to upgrade? If not, it is a simple enough tweak to support 3.10 by changing it back to `set_property`.

**Comment by tastytea** [comment]
The CMake in Ubuntu bionic (18.04), the previous LTS, is 3.10.2. It would be nice to support that, but I'm only using it for CI, so I don't really *need* it.

Whatever you decide, could you add `cmake_minimum_required` to the file?

**Comment by tastytea** [comment]
Thank you, it works with 6cd5e7ff3d7827c744959fa5a296fac792fdb71c.
